task:
  name: Emulator tests
  env:
    CIRRUS_CLONE_SUBMODULES: "true"
  container:
    image: ghcr.io/cirruslabs/android-sdk:33
    cpu: 4
    memory: 12G
    kvm: "true"
  check_script:
      - ./gradlew pixel2api30DebugAndroidTest
